import { invoke } from "@tauri-apps/api/core";
import {
  AudioLines, Bluetooth, BrainCircuit, Camera, Check, ChevronDown, ChevronRight,
  CircleAlert, CloudRain, createIcons, Database, Download, FlaskConical,
  Gift, Glasses, Heart, House, Leaf, Link, ListTodo, Orbit, Radio,
  Mic, RefreshCw, ScanFace, Search, Settings2, ShieldCheck, Telescope,
  Trash2, UserRound, UserRoundPlus, UsersRound, X,
} from "lucide";
import { modelHub } from "./utils/models";
import { analyzeConversation } from "./utils/memoryPlanner";
import { analyzeMood, moodKinds, type MoodAnalysis, type MoodKind } from "./utils/moodPlanner";
import "./styles.css";

type Tab="topia"|"quests"|"people"|"settings";
type Setting="glasses"|"intelligence"|"memory"|"testing";
type PersonPanel="quests"|"memories"|"profile";
type QuestFilter="active"|"done"|"all";
type GlassSettings={intervalSeconds:number;width:number;quality:number;personAlert:"poster"|"quiet"};
type Metric={request_id:number;mode:"cold"|"hot";bytes:number;camera_open_ms:number;warmup_ms:number;capture_ms:number;transfer_ms:number;e2e_ms:number};
type Face={request_id:number;detected_count:number;eligible_count:number;recognition_invoked:boolean;matches:{decision:string;person_id:string|null;score:number}[];detection_ms:number;recognition_ms:number;recognizer_load_ms:number;processing_total_ms:number};
type Recording={recording_id:number;bytes:number;sample_rate:number;channels:number;encoding:string;duration_ms:number;transfer_ms:number;path:string};
type LocalAsrResult={text:string;provider:string;model:string;side:"edge";latency_ms:number;audio_ms:number;prefill_ms:number;decode_ms:number;audio_duration_ms:number;realtime_factor:number;prompt_tokens:number;generated_tokens:number;status:number;model_load_ms:number};
type MoodSpeechResult={transcript:string;confidence:number};
type MoodSnapshot=MoodAnalysis&{transcript:string;model:string;analyzedAt:string};
type MoodPhase="idle"|"listening"|"analyzing"|"result"|"error";
type ModelDownloadStatus={model_id:string;repository_url:string;state:string;ready:boolean;automatic:boolean;downloaded_bytes:number;total_bytes:number;completed_files:number;file_count:number;install_path:string;last_error:string|null};
type State={phase:string;session_id:string|null;transport:string;completed_captures:number;detail:string;last_error:string|null;last_capture:Metric|null;face_processing?:string;face_error?:string|null;last_face?:Face|null;last_recording?:Recording|null;recording_processing?:string};
type Quest={id:string;group:string;title:string;meta:string;body:string;priority:string;progress:number;steps:string[];person?:string;personId?:string;parentId?:string;reward:string};
type Person={id:string;name:string;role:string;affinity:number;tone:string;quote:string;story:string;quests:string[];seen:string};
type Memory={id:string;time:string;title:string;meta:string;kind:"task"|"recording"|"person"|"mood";summary?:string;transcript?:string;personIds?:string[];taskIds?:string[];mood?:MoodKind;intensity?:number};

const moodProfiles:Record<MoodKind,{label:string;weather:string;effect:string}>={
 joyful:{label:"愉快",weather:"晴光",effect:"阳光与闪光"},calm:{label:"平静",weather:"微风",effect:"柔和云流"},sad:{label:"难过",weather:"下雨",effect:"雨滴与冷色天空"},anxious:{label:"焦虑",weather:"疾风",effect:"快速流云"},angry:{label:"生气",weather:"雷云",effect:"脉冲与风暴"},tired:{label:"疲惫",weather:"夜雾",effect:"薄雾与星光"},neutral:{label:"平常",weather:"晴间云",effect:"自然天气"},
};
const moodEmoji:Record<MoodKind,string>={joyful:"😄",calm:"😌",sad:"😢",anxious:"😥",angry:"😠",tired:"😴",neutral:"🙂"};

const personIdByName:Record<string,string>={"林澄":"lin","周野":"zhou","沈弦":"shen","妈妈":"mom"};
const localModelRepositories=[
 {id:"huangzhengxiang/Qwen3-ASR-0.6B-INT8-MNN",name:"Qwen3-ASR 0.6B INT8",kind:"本地语音识别",install:"auto" as const},
 {id:"MNN/Qwen3-1.7B-MNN",name:"Qwen3 1.7B",kind:"本地通用语言模型 · 4-bit",install:"manual" as const},
 {id:"MNN/Qwen3-VL-2B-Instruct-MNN",name:"Qwen3-VL 2B Instruct",kind:"本地视觉理解",install:"manual" as const},
 {id:"MNN/Qwen3-VL-4B-Instruct-MNN",name:"Qwen3-VL 4B Instruct",kind:"本地视觉理解 · 高质量",install:"manual" as const},
 {id:"huangzhengxiang/Qwen3-TTS-0.6B-Base-FP16-MNN",name:"Qwen3-TTS 0.6B Base FP16",kind:"本地语音合成",install:"manual" as const},
];

const starterQuests:Quest[]=[
 {id:"garden",group:"世界任务",title:"让阳台重新生长",meta:"家园 · 长线",body:"把那块闲置的阳台变成一个会随季节变化的小花园。先从容易照料的香草开始。",priority:"首要",progress:45,steps:["测量日照与可用面积","和林澄确认周末花市时间","购买薄荷与迷迭香","完成第一周浇水记录"],person:"林澄",personId:"lin",reward:"记忆组件 · 风铃苗圃"},
 {id:"album",group:"世界任务",title:"整理母亲的旧相册",meta:"关系 · 家人",body:"将散落的家庭照片按年份整理，并记录每张照片背后的故事。",priority:"普通",progress:20,steps:["收集三处旧相册","扫描 1998—2005 年照片","周日致电妈妈询问背景"],person:"妈妈",personId:"mom",reward:"人物故事 · 旧日夏天"},
 {id:"app",group:"世界任务",title:"完成 RealTopia 原型",meta:"创造 · 项目",body:"打通眼镜与手机的日常记录体验，让技术悄悄退到生活后面。",priority:"首要",progress:68,steps:["双端视觉统一","任务与人物关联","真机延迟回归","邀请两位朋友试用"],reward:"场景组件 · 微光观测站"},
 {id:"book",group:"突发任务",title:"把书还给周野",meta:"今天 · 18:30 前",body:"下班路过青苔书店时把《看不见的城市》还给周野。",priority:"首要",progress:0,steps:["出门时带上书","18:30 前到青苔书店"],person:"周野",personId:"zhou",reward:"好感度 +12"},
 {id:"dentist",group:"突发任务",title:"预约牙医复诊",meta:"今天 · 5 分钟",body:"打电话确认下周三下午是否有空位。",priority:"普通",progress:0,steps:["致电诊所","写入日历"],reward:"生命力 +5"}
];
function loadQuests(){try{const value=JSON.parse(localStorage.getItem("realtopia.quests")??"[]") as Quest[];return (value.length?value:structuredClone(starterQuests)).map(item=>({...item,personId:item.personId??(item.person?personIdByName[item.person]:undefined)}))}catch{return structuredClone(starterQuests)}}
function saveQuests(){localStorage.setItem("realtopia.quests",JSON.stringify(quests))}
let quests=loadQuests();
const starterMemories:Memory[]=[
 {id:"seed-bookstore",time:"今天 17:42",title:"青苔书店的雨",meta:"人物 · 周野 / 地点 · 老街",kind:"person"},
 {id:"seed-garden",time:"08.08 21:06",title:"阳台花园的计划",meta:"人物 · 林澄 / 关联任务 2",kind:"task"},
 {id:"seed-e2e",time:"08.06 09:13",title:"第一次眼镜端 E2E 测试",meta:"项目 · RealTopia / 图片 6",kind:"recording"}
];
function loadMemories(){try{const raw=localStorage.getItem("realtopia.memories");return raw===null?structuredClone(starterMemories):JSON.parse(raw) as Memory[]}catch{return structuredClone(starterMemories)}}
function saveMemories(){localStorage.setItem("realtopia.memories",JSON.stringify(memories.slice(0,200)))}
let memories=loadMemories();
const starterPeople:Person[]=[
 {id:"lin",name:"林澄",role:"植物研究员 / 老朋友",affinity:86,tone:"jade",quote:"等迷迭香长高一点，我们就能闻着夏天做饭了。",story:"你们在大学的旧温室认识。她总能记住每一株植物的名字，也总会在你忙得忘记吃饭时发来一张晚霞。",quests:["让阳台重新生长","周末去城南花市"],seen:"上次见面 · 3 天前"},
 {id:"zhou",name:"周野",role:"青苔书店主理人",affinity:64,tone:"amber",quote:"书不用急着还，故事看完就好。",story:"住在老街尽头的书店老板。认识之后，你的借阅时间总比别人长一些。",quests:["把书还给周野"],seen:"上次见面 · 昨天"},
 {id:"shen",name:"沈弦",role:"独立音乐人",affinity:41,tone:"violet",quote:"雨落在不同屋檐上，是不同的节拍。",story:"在一次小型演出后认识。她正在收集城市里被忽略的声音。",quests:["整理城市声音采样"],seen:"上次见面 · 12 天前"},
 {id:"mom",name:"妈妈",role:"家人",affinity:92,tone:"rose",quote:"旧照片别扔，背后写着日期呢。",story:"她总说家里的事不用挂心，但会把每一次通话的日期写在厨房日历上。",quests:["整理母亲的旧相册"],seen:"上次通话 · 5 天前"}
];
function loadPeople(){try{const value=JSON.parse(localStorage.getItem("realtopia.people")??"[]") as Person[];return value.length?value:structuredClone(starterPeople)}catch{return structuredClone(starterPeople)}}
function savePeople(){localStorage.setItem("realtopia.people",JSON.stringify(people))}
let people=loadPeople();
function loadGlassSettings(){try{return {...{intervalSeconds:15,width:4032,quality:90,personAlert:"poster" as const},...JSON.parse(localStorage.getItem("realtopia.glassSettings")??"{}")} as GlassSettings}catch{return {intervalSeconds:15,width:4032,quality:90,personAlert:"poster"}}}
function saveGlassSettings(){localStorage.setItem("realtopia.glassSettings",JSON.stringify(glassSettings))}
let glassSettings=loadGlassSettings();

const emptyMood:MoodSnapshot={mood:"neutral",intensity:20,summary:"今天还没有记录心情",support:"说说此刻的感受，让 Topia 回应你。",transcript:"",model:"",analyzedAt:""};
function loadMood():MoodSnapshot{try{const value=JSON.parse(localStorage.getItem("realtopia.mood")??"null") as Partial<MoodSnapshot>|null;if(!value||!moodKinds.includes(value.mood as MoodKind))return {...emptyMood};const text=(input:unknown,fallback:string,max:number)=>typeof input==="string"?input.slice(0,max):fallback;return {mood:value.mood as MoodKind,intensity:Math.max(0,Math.min(100,Number(value.intensity)||0)),summary:text(value.summary,emptyMood.summary,60),support:text(value.support,emptyMood.support,90),transcript:text(value.transcript,"",4000),model:text(value.model,"",100),analyzedAt:text(value.analyzedAt,"",40)}}catch{return {...emptyMood}}}
function saveMood(){localStorage.setItem("realtopia.mood",JSON.stringify(currentMood))}
let currentMood=loadMood(),moodDialogOpen=false,moodPhase:MoodPhase="idle",moodTranscript="",moodError="";

const params=new URLSearchParams(location.search);const screen=params.get("screen")??"topia";
let tab:Tab=(["topia","quests","people","settings"].includes(screen)?screen:"topia") as Tab;
let setting:Setting=(["glasses","intelligence","memory","testing"].includes(screen)?screen:"glasses") as Setting;
if(["glasses","intelligence","memory","testing"].includes(screen))tab="settings";
let quest=quests[0],questFilter:QuestFilter="active",person=people[0],peoplePanel:PersonPanel="quests",collapsed=new Set<string>(),perception=localStorage.getItem("realtopia.perception")!=="off";
let memoryQuery="",selectedMemoryId=memories[0]?.id??"";
let memoryDrawerOpen=false;
let state:State={phase:"idle",session_id:null,transport:"未连接",completed_captures:0,detail:"",last_error:null,last_capture:null};
let asrDownload:ModelDownloadStatus|null=null,lastModelStatusFetch=0;
let logs=["系统启动 · 记忆索引加载完成","端侧 MNN 人物模型待命","等待连接眼镜"];
let connecting=false;
let syncedSessionId:string|null=null;
const processingRecordings=new Set<number>();
const recordingRetryAfter=new Map<number,number>();
let disposeTopia:(()=>void)|null=null;
let renderVersion=0;
const app=document.querySelector<HTMLDivElement>("#app")!;

const lucideIcons={AudioLines,Bluetooth,BrainCircuit,Camera,Check,ChevronDown,ChevronRight,CircleAlert,CloudRain,Database,Download,FlaskConical,Gift,Glasses,Heart,House,Leaf,Link,ListTodo,Mic,Orbit,Radio,RefreshCw,ScanFace,Search,Settings2,ShieldCheck,Telescope,Trash2,UserRound,UserRoundPlus,UsersRound,X};
const icon=(name:keyof typeof lucideIcons,className="")=>`<i class="ui-icon ${className}" data-lucide="${name}"></i>`;

function frame(body:string){const nav:[[Tab,keyof typeof lucideIcons,string],...[Tab,keyof typeof lucideIcons,string][]]=[["topia","House","Topia"],["quests","ListTodo","任务"],["people","UsersRound","人物"],["settings","Settings2","设置"]];return `<div class="shell"><header class="top"><button class="brand" data-tab="topia"><span class="brand-mark">${icon("Orbit")}</span><span><b>RealTopia</b></span></button><nav>${nav.map(([id,glyph,label])=>`<button data-tab="${id}" class="${tab===id?"active":""}">${icon(glyph)}<span>${label}</span>${id==="quests"?`<em>${quests.filter(item=>item.progress<100).length}</em>`:""}</button>`).join("")}</nav><div class="system"><b>12级</b><i class="${state.phase}"></i><span>${new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</span></div></header><main class="body">${body}</main><div class="toast"></div></div>`}
function moodWeather(){const count=currentMood.mood==="neutral"?0:30,particles=Array.from({length:count},(_,index)=>`<i style="--x:${(index*37)%101}%;--delay:-${(index%13)*.31}s;--speed:${1.1+(index%7)*.13}s"></i>`).join("");return `<div class="mood-weather mood-${currentMood.mood}" aria-hidden="true">${particles}</div>`}
function moodDialog(){if(!moodDialogOpen)return "";const profile=moodProfiles[currentMood.mood],privacy=`<p class="mood-privacy">${icon("ShieldCheck")}录音由本机 Qwen3-ASR 转写后删除，只有转写文字会发送给云端 LLM。</p>`;let content="";if(moodPhase==="listening")content=`<div class="mood-listening">${icon("Mic")}<div class="mood-wave">${Array.from({length:9},()=>"<i></i>").join("")}</div><h3>正在听你说</h3><p>自然地说说此刻的感受，说完后点击完成。</p><div class="buttons"><button id="cancel-mood-listen">取消</button><button class="primary" id="finish-mood-listen">说完了</button></div></div>`;else if(moodPhase==="analyzing")content=`<div class="mood-analyzing"><span></span><h3>正在理解这份心情</h3><p>云端只会返回心情类别、强度和一句温和回应。</p></div>`;else if(moodPhase==="result")content=`<div class="mood-result"><span class="mood-result-icon">${currentMood.mood==="sad"?icon("CloudRain"):icon("Heart")}</span><small>${profile.weather} · 强度 ${currentMood.intensity}</small><h3>${profile.label}</h3><p>${safe(currentMood.summary)}</p><blockquote>${safe(currentMood.support)}</blockquote><button class="primary" id="finish-mood">看看变化</button></div>`;else if(moodPhase==="error")content=`<div class="mood-error"><span>${icon("CircleAlert")}</span><h3>这次没有分析成功</h3><p>${safe(moodError)}</p><div class="buttons"><button id="open-cloud-settings">检查云端配置</button><button class="primary" id="start-mood-listen">重新录入</button></div></div>`;else content=`<div class="mood-intro"><span class="mood-orb">${icon("Heart")}</span><small>当前天气 · ${profile.weather}</small><h3>${safe(currentMood.summary)}</h3><p>${safe(currentMood.support)}</p><button class="primary" id="start-mood-listen">${icon("Mic")}按下后说话</button>${privacy}</div>`;return `<div class="mood-dialog-backdrop"><section class="mood-dialog" role="dialog" aria-modal="true" aria-labelledby="mood-dialog-title"><header><div><small>心情记录</small><h2 id="mood-dialog-title">让世界回应此刻</h2></div><button id="close-mood" aria-label="关闭心情记录">${icon("X")}</button></header>${content}</section></div>`}
function topia(){const vitality=Math.min(99,48+Math.round(quests.reduce((sum,item)=>sum+item.progress,0)/Math.max(1,quests.length)/2)+Math.min(20,memories.length));const stage=vitality>=80?3:vitality>=60?2:1,focus=quests.find(item=>item.progress<100)??quests[0],profile=moodProfiles[currentMood.mood];return frame(`<div class="topia"><section class="world stage-${stage} mood-${currentMood.mood}" style="--mood-intensity:${currentMood.intensity/100}"><canvas id="topia-canvas" aria-label="云上漂流屋三维场景"></canvas>${moodWeather()}<button class="landmark garden">${icon("Leaf")}<span><b>窗边花圃</b><small>生长 ${vitality}%</small></span></button><button class="landmark lab">${icon("Telescope")}<span><b>星图桌</b><small>${stage===3?"微光已点亮":"正在布置"}</small></span></button><div class="world-title"><h1>云上漂流屋</h1><p>${memories.length} 段记忆正在装点房间</p></div><button class="mood-indicator" id="world-mood" aria-label="当前心情：${profile.label}，${profile.weather}" title="${profile.label} · ${profile.weather}">${moodEmoji[currentMood.mood]}</button></section><div class="today-column"><div class="quick-actions" aria-label="快速记录"><button id="record-task" aria-label="记录任务">${icon("ListTodo")}记录任务</button><button id="record-mood" aria-label="记录心情">${icon("Heart")}记录心情</button></div><aside class="today panel"><div class="today-head"><b>今天</b><small>8月9日</small></div><h2>当前旅程</h2><div class="life"><span>生命力 <b>${vitality}</b></span><i><em style="width:${vitality}%"></em></i></div><button class="today-item" data-tab="quests"><span class="item-icon gold">${icon("CircleAlert")}</span><span><b>${focus.title}</b><small>${focus.meta}</small></span>${icon("ChevronRight")}</button><button class="today-item" id="today-mood"><span class="item-icon avatar">${icon("Heart")}</span><span><b>${safe(currentMood.summary)}</b><small>${profile.label} · ${profile.weather}</small></span>${icon("ChevronRight")}</button></aside></div>${moodDialog()}</div>`)}

function questsView(){
 const completed=Math.round(quest.progress*quest.steps.length/100),parent=quest.parentId?quests.find(item=>item.id===quest.parentId):null,children=quests.filter(item=>item.parentId===quest.id);
 const filtered=quests.filter(item=>questFilter==="all"||(questFilter==="done"?item.progress===100:item.progress<100));
 const groups=["世界任务","突发任务"].map(g=>`<section class="q-group"><button class="group" data-group="${g}"><span>${icon("ListTodo")}<b>${g}</b><small>${filtered.filter(x=>x.group===g).length} 项</small></span>${icon(collapsed.has(g)?"ChevronRight":"ChevronDown")}</button>${collapsed.has(g)?"":filtered.filter(x=>x.group===g).map(x=>`<button class="q-item ${quest.id===x.id?"active":""}" data-quest="${x.id}"><i class="priority ${x.priority}"></i><span><b>${x.parentId?"子任务 · ":""}${x.title}</b><small>${x.meta}${x.person?` · ${x.person}`:""}</small></span><em>${x.progress}%</em></button>`).join("")}</section>`).join("");
 return frame(`<div class="quests"><aside class="q-list"><div class="q-list-head"><div class="page-head"><h1>任务</h1></div><div class="chips quest-filters"><button data-quest-filter="active" class="${questFilter==="active"?"active":""}">进行中</button><button data-quest-filter="done" class="${questFilter==="done"?"active":""}">已完成</button><button data-quest-filter="all" class="${questFilter==="all"?"active":""}">全部</button></div></div><div class="q-scroll">${groups}</div></aside><article class="q-detail"><div class="q-tags"><span>${icon("ListTodo")}${quest.group}</span><b>${quest.priority}优先级</b></div><h1>${quest.title}</h1><small>${quest.meta}${quest.person?`　·　关联人物 ${quest.person}`:""}</small>${parent?`<button class="parent-link" data-quest="${parent.id}">${icon("Link")}父任务　<b>${parent.title}</b></button>`:""}<p>${quest.body}</p><section class="task-status"><div class="q-progress"><span>任务进度</span><b>${quest.progress}%</b></div><div class="meter"><i style="width:${quest.progress}%"></i></div><div class="clue-head"><h3>行动线索</h3><small>${completed} / ${quest.steps.length} 已完成</small></div><div class="steps">${quest.steps.map((s,i)=>`<button class="step ${i<completed?"done":""}" data-step="${i}"><span class="step-check">${i<completed?icon("Check"):""}</span>${s}</button>`).join("")}</div></section>${children.length?`<h3>子任务</h3>${children.map(item=>`<button class="child-link" data-quest="${item.id}"><i>${item.progress}%</i><span>${item.title}</span>${icon("ChevronRight")}</button>`).join("")}`:""}<div class="reward"><span class="reward-icon">${icon("Gift")}</span><span><small>完成奖励</small><b>${quest.reward}</b></span></div></article></div>`)
}

function portrait(p:Person,big=false){return `<div class="portrait ${p.tone} ${big?"big":""}">${icon("UserRound")}<span>${p.name.slice(-1)}</span></div>`}
function personPanelContent(value:Person){if(peoplePanel==="memories"){const related=memories.filter(item=>item.personIds?.includes(value.id)||item.title.includes(value.name)||item.meta.includes(value.name));return related.length?related.slice(0,6).map(item=>`<button class="linked memory-link" data-memory="${item.id}"><span class="linked-icon blue">${icon("Database")}</span><span><b>${item.title}</b><small>${item.time} · ${item.meta}</small></span>${icon("ChevronRight")}</button>`).join(""):`<p class="empty-panel">眼镜识别或对话总结后，共同记忆会出现在这里。</p>`}if(peoplePanel==="profile")return `<div class="profile-grid"><span><small>人物 ID</small><b>${value.id}</b></span><span><small>最近记录</small><b>${value.seen}</b></span><span><small>人脸模板</small><b>MNN ArcFace 512D</b></span><span><small>隐私范围</small><b>仅本机</b></span></div>`;return value.quests.length?value.quests.map((title,index)=>{const item=quests.find(task=>task.title===title);return `<button class="linked" ${item?`data-quest="${item.id}" data-open-quest="true"`:""}><span class="linked-icon ${index?"blue":"gold"}">${icon(index?"Link":"CircleAlert")}</span><span><b>${title}</b><small>${item?`${item.group} · ${item.progress}%`:"人物长期线索"}</small></span>${icon("ChevronRight")}</button>`}).join(""):`<p class="empty-panel">暂时没有关联任务。</p>`}
function peopleView(){const live=state.last_face,relatedMemories=memories.filter(item=>item.personIds?.includes(person.id)||item.title.includes(person.name)||item.meta.includes(person.name)).length;return frame(`<div class="people"><aside class="p-list"><div class="p-list-head"><div class="page-head"><h1>人物</h1></div><div class="chips"><b>最近相遇</b><span>全部人物</span><span>等待相认</span></div></div><div class="p-grid">${people.map(p=>`<button class="p-card ${person.id===p.id?"active":""}" data-person="${p.id}">${portrait(p)}<span><b>${p.name}</b><small>${p.role}</small><em>${icon("Heart")}${p.affinity}</em></span></button>`).join("")}</div><button class="import" id="enroll-person">${icon("UserRoundPlus")}<b>录入人物</b><small>${live?.eligible_count?`检测到 ${live.eligible_count} 张可用人脸`:'请先拍摄清晰正脸'}</small></button></aside><article class="p-info"><section class="person-overview"><div class="p-hero">${portrait(person,true)}<small>第 ${String(people.indexOf(person)+1).padStart(2,"0")} 位</small></div><div class="person-bio"><h1>${person.name}</h1><p class="role">${person.role}</p><div class="affinity"><span>${icon("Heart")}好感度</span><b>${person.affinity}<small>/100</small></b><i><em style="width:${person.affinity}%"></em></i></div><blockquote>“${person.quote}”</blockquote><p>${person.story}</p></div></section><div class="p-tabs"><button data-person-panel="quests" class="${peoplePanel==="quests"?"active":""}">关联任务 ${person.quests.length}</button><button data-person-panel="memories" class="${peoplePanel==="memories"?"active":""}">共同记忆 ${relatedMemories}</button><button data-person-panel="profile" class="${peoplePanel==="profile"?"active":""}">人物档案</button></div><div class="person-related">${personPanelContent(person)}</div><small class="seen">${icon("ScanFace")}${person.seen} · 由眼镜感知</small>${live?`<div class="face-live"><b>最近识别 #${live.request_id}</b><span>检测 ${live.detected_count} · 可匹配 ${live.eligible_count} · ${live.processing_total_ms} 毫秒</span></div>`:""}</article></div>`)}

const toggle=(label:string,on:boolean,id:string)=>`<label class="toggle"><span>${label}</span><input id="${id}" type="checkbox" ${on?"checked":""}><i></i></label>`;
const card=(title:string,_sub:string,content:string)=>`<section class="s-card"><h3>${title}</h3>${content}</section>`;
function glasses(){const ready=state.phase==="ready";return `<div class="setting-view"><div class="setting-head"><h1>眼镜</h1></div>${card("眼镜连接","",`<div class="device"><span class="device-icon">${icon("Glasses")}</span><span><b>${ready?"已连接 · RealTopia Glass":"等待连接 · RealTopia Glass"}</b><small>${ready?state.transport:"蓝牙控制与直连传输"}</small></span><em>${ready?"在线":"离线"}</em></div><div class="buttons"><button id="choose">${icon("Glasses")}选择眼镜</button><button id="bt">${icon("Bluetooth")}蓝牙设置</button></div>`)}${card("感知与拍摄","",`${toggle("持续拍摄感知",perception,"perception")}<label class="range"><span>自动拍摄间隔</span><input id="capture-interval" type="range" min="5" max="60" value="${glassSettings.intervalSeconds}"><b id="capture-interval-label">${glassSettings.intervalSeconds} 秒</b></label><div class="row"><span><b>物理按钮即时拍摄</b><small>短按拍照，长按记录对话</small></span><em>${icon("Camera")}已启用</em></div>`)}${card("图像参数","",`<label class="range"><span>图片质量</span><input id="capture-quality" type="range" min="50" max="100" value="${glassSettings.quality}"><b id="capture-quality-label">${glassSettings.quality}</b></label><label class="select"><span>拍摄分辨率</span><select id="capture-width"><option value="4032" ${glassSettings.width===4032?"selected":""}>4032 × 3024</option><option value="2560" ${glassSettings.width===2560?"selected":""}>2560 长边</option><option value="1920" ${glassSettings.width===1920?"selected":""}>1920 长边</option><option value="1280" ${glassSettings.width===1280?"selected":""}>1280 长边</option></select></label><label class="select"><span>人物出现提醒</span><select id="person-alert"><option value="poster" ${glassSettings.personAlert==="poster"?"selected":""}>定格海报与轻提示</option><option value="quiet" ${glassSettings.personAlert==="quiet"?"selected":""}>仅眼镜静默显示</option></select></label>`)}</div>`}
function formatBytes(value:number){if(value<=0)return "—";const units=["B","KB","MB","GB"];let size=value,index=0;while(size>=1024&&index<units.length-1){size/=1024;index++}return `${size.toFixed(index<2?0:2)} ${units[index]}`}
function asrStatusLabel(){if(!asrDownload)return "检测中";const labels:Record<string,string>={ready:"已安装",checking:"检查中",downloading:"下载中",queued:"已排队",waiting_network:"等待联网",error:"下载失败",mobile_only:"仅手机端"};return labels[asrDownload.state]??asrDownload.state}
function modelRepositoryRows(){return localModelRepositories.map(model=>{const automatic=model.install==="auto",progress=automatic&&asrDownload?.total_bytes?Math.min(100,Math.round(asrDownload.downloaded_bytes/asrDownload.total_bytes*100)):0,detail=automatic?`${asrStatusLabel()} · ${asrDownload?.total_bytes?`${formatBytes(asrDownload.downloaded_bytes)} / ${formatBytes(asrDownload.total_bytes)}`:"约 1.33 GB · 联网后自动下载"}`:"按需下载 · 不占用 APK 体积";return `<div class="model-download"><span class="model-icon ${automatic?"edge":"cloud-model"}">${icon(automatic?"AudioLines":"Download")}</span><span><b>${model.name}</b><small>${model.kind} · ${detail}</small>${automatic&&asrDownload?.total_bytes?`<i class="download-progress"><em style="width:${progress}%"></em></i>`:""}</span><div class="model-actions">${automatic&&!asrDownload?.ready?`<button id="start-asr-download">${icon("Download")}${asrDownload?.state==="error"?"重试":"立即下载"}</button>`:""}<button data-model-repo="${model.id}">${icon("Link")}ModelScope</button></div></div>`}).join("")}
function intelligence(){const m=modelHub.load();return `<div class="setting-view"><div class="setting-head"><h1>智能</h1></div>${card("ModelScope 端侧模型","",`${modelRepositoryRows()}<div class="model-download-note">${icon("ShieldCheck")}大模型不会打进 APK；ASR 在应用首次联网后自动下载到应用私有目录，卸载应用时一并清除。</div>`)}${card("云侧模型","",`<div class="model"><span class="model-icon cloud-model">${icon("BrainCircuit")}</span><span><b>${m.cloud.provider}</b><small>${m.cloud.baseUrl} · ${m.cloud.hasApiKey?"密钥已安全保存":"尚未配置密钥"}</small></span><button id="test-model">${icon("Radio")}测试连接</button></div><label class="select"><span>服务商</span><input id="model-provider"></label><label class="select"><span>接口地址</span><input id="model-base-url" inputmode="url"></label><label class="select"><span>默认推理模型</span><input id="model-name"></label><label class="select"><span>录音转写模型</span><input id="model-stt"></label><label class="secret"><span>访问密钥</span><input id="model-key" type="password" autocomplete="off"><button id="show-key">显示</button></label><div class="model-download-note">${icon("ShieldCheck")}密钥只在 Android 原生层解密并发起 HTTPS 请求，不返回 WebView、不写 localStorage 或日志；留空保存不会替换已有密钥。</div><div class="buttons right">${m.cloud.hasApiKey?`<button id="clear-model-key">清除密钥</button>`:""}<button class="primary" id="save-model">${icon("ShieldCheck")}安全保存</button></div>`)}${card("智能路由","",`${toggle("隐私内容始终使用端侧",m.routing.privateOnEdge,"private")}${toggle("复杂任务允许使用云端",m.routing.complexOnCloud,"cloud")}`)}</div>`}
function memory(){const query=memoryQuery.trim().toLowerCase(),filtered=memories.filter(item=>!query||`${item.title} ${item.meta} ${item.summary??""} ${item.transcript??""}`.toLowerCase().includes(query)),selected=memories.find(item=>item.id===selectedMemoryId)??filtered[0],relatedPeople=selected?.personIds?.map(id=>people.find(item=>item.id===id)?.name).filter(Boolean)??[],relatedTasks=selected?.taskIds?.map(id=>quests.find(item=>item.id===id)?.title).filter(Boolean)??[],drawer=memoryDrawerOpen&&selected?`<button class="memory-drawer-backdrop" data-close-memory aria-label="关闭记忆详情"></button><article class="memory-drawer"><div class="drawer-head"><small>${selected.time}</small><button data-close-memory>关闭</button></div><h3>${selected.title}</h3><p>${selected.summary??selected.meta}</p>${selected.transcript?`<blockquote>${selected.transcript}</blockquote>`:""}<div class="memory-relations"><span>人物　${relatedPeople.join("、")||"未关联"}</span><span>任务　${relatedTasks.join("、")||"未关联"}</span></div><button class="danger-inline" id="delete-memory">${icon("Trash2")}删除此条记忆</button></article>`:"";return `<div class="setting-view"><div class="setting-head"><h1>记忆</h1></div>${card("搜索记忆","",`<label class="search">${icon("Search")}<input id="memory-search" value="${safe(memoryQuery)}"></label>`)}${card("记忆条目","",`<div class="memory-manager"><div class="mem-list">${filtered.slice(0,20).map(item=>`<button data-memory="${item.id}"><time>${item.time}</time><span><b>${item.title}</b><small>${item.meta}</small></span>${icon("ChevronRight")}</button>`).join("")||`<p class="empty-panel">没有匹配的记忆。</p>`}</div></div>`)}${card("存储与隐私","",`<div class="row"><span><b>自动提炼</b><small>仅在配置模型后处理，原始媒体默认留在本机</small></span><em>${icon("ShieldCheck")}本机</em></div><div class="buttons"><button id="export-memory">${icon("Download")}导出记忆档案</button><button id="clear-memory" class="danger">${icon("Trash2")}清除全部记忆</button></div>`)}${drawer}</div>`}
function testing(){const m=state.last_capture,r=state.last_recording;const testItems:[[string,keyof typeof lucideIcons,string,string],...[string,keyof typeof lucideIcons,string,string][]]=[["cold","Camera","冷启动拍摄","重启相机并预热"],["hot","ScanFace","热拍摄","复用相机会话"],["bench","FlaskConical","自动端到端基准","1 次冷拍与 5 次热拍"],["audio","AudioLines","对话录音","长按眼镜物理按钮"]];return `<div class="setting-view"><div class="setting-head"><h1>测试</h1></div>${card("快捷测试","眼镜连接后即可运行",`<div class="tests">${testItems.map(item=>`<button data-test="${item[0]}"><span>${icon(item[1])}</span><b>${item[2]}</b><small>${item[3]}</small></button>`).join("")}</div>`)}${card("最近一次端到端测试",m?`请求 #${m.request_id} · ${m.mode==="hot"?"热拍":"冷拍"}`:"尚无本次会话数据",`<div class="latency"><span><b>${m?.e2e_ms??"—"}</b><small>毫秒</small></span>${[["打开",m?.camera_open_ms],["预热",m?.warmup_ms],["拍摄",m?.capture_ms],["传输",m?.transfer_ms]].map((x,i)=>`<i><em style="height:${25+i*14}%"></em><small>${x[0]}<br>${x[1]??"—"}</small></i>`).join("")}</div>`)}${card("最近一段对话",r?`录音 #${r.recording_id} · ${(r.duration_ms/1000).toFixed(1)} 秒`:"等待眼镜端录音",`<div class="recording-state"><span class="recording-icon">${icon("AudioLines")}</span><span><b>${r?`${Math.round(r.bytes/1024)} KB · ${r.sample_rate/1000} kHz ${r.encoding}`:"长按眼镜按钮开始，松开发送"}</b><small>${r?`直连传输 ${r.transfer_ms} 毫秒 · ${state.recording_processing}`:"录音保存在手机并进入处理队列"}</small></span></div>`)}${card("运行日志","",`<div class="terminal">${logs.map((l,i)=>`<p><time>${new Date(Date.now()-i*30000).toLocaleTimeString("zh-CN")}</time>${l}</p>`).join("")}</div><div class="buttons right"><button id="clear">清空</button><button class="primary" id="refresh">${icon("RefreshCw")}刷新状态</button></div>`)}</div>`}
function settings(){const items:[[Setting,keyof typeof lucideIcons,string],...[Setting,keyof typeof lucideIcons,string][]]=[["glasses","Glasses","眼镜"],["intelligence","BrainCircuit","智能"],["memory","Database","记忆"],["testing","FlaskConical","测试"]];return frame(`<div class="settings"><aside class="s-nav"><div class="page-head"><h1>设置</h1></div><nav>${items.map(x=>`<button data-setting="${x[0]}" class="${setting===x[0]?"active":""}"><span class="nav-icon">${icon(x[1])}</span><span><b>${x[2]}</b></span>${icon("ChevronRight")}</button>`).join("")}</nav></aside><section class="s-content">${setting==="glasses"?glasses():setting==="intelligence"?intelligence():setting==="memory"?memory():testing()}</section></div>`)}

function render(){const version=++renderVersion;disposeTopia?.();disposeTopia=null;app.innerHTML=tab==="topia"?topia():tab==="quests"?questsView():tab==="people"?peopleView():settings();createIcons({icons:lucideIcons,attrs:{"stroke-width":"2.25","aria-hidden":"true"}});bind();const canvas=document.querySelector<HTMLCanvasElement>("#topia-canvas");if(canvas)void import("./utils/topiaScene").then(({mountTopiaScene})=>{if(version===renderVersion&&canvas.isConnected)disposeTopia=mountTopiaScene(canvas,currentMood.mood,currentMood.intensity)})}
function toast(s:string){const el=document.querySelector<HTMLElement>(".toast");if(!el)return;el.textContent=s;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2000)}
function ingestState(){
 let changed=false;const time=new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});
 const recording=state.last_recording;if(recording&&!memories.some(item=>item.id===`recording-${recording.recording_id}`)){memories.unshift({id:`recording-${recording.recording_id}`,time,title:`眼镜对话录音 #${recording.recording_id}`,meta:`${(recording.duration_ms/1000).toFixed(1)} 秒 · ${Math.round(recording.bytes/1024)} KB · 待转写`,kind:"recording"});changed=true}
 const match=state.last_face?.matches.find(item=>item.decision==="known"&&item.person_id);if(match&&state.last_face){const id=`face-${state.last_face.request_id}-${match.person_id}`;if(!memories.some(item=>item.id===id)){const known=people.find(item=>item.id===match.person_id);memories.unshift({id,time,title:`再次遇见 ${known?.name??match.person_id}`,meta:`眼镜人物识别 · 相似度 ${match.score.toFixed(3)}`,kind:"person"});changed=true}}
 if(changed)saveMemories();return changed;
}
async function processRecording(recording:Recording){
 if(processingRecordings.has(recording.recording_id)||(recordingRetryAfter.get(recording.recording_id)??0)>Date.now())return;processingRecordings.add(recording.recording_id);
 try{await invoke("mark_recording_processed",{recordingId:recording.recording_id,status:"local ASR transcribing"});const local=await invoke<LocalAsrResult>("transcribe_recording",{recordingId:recording.recording_id}),transcript={text:local.text,provider:local.provider,model:local.model,side:"edge" as const,latencyMs:local.latency_ms};logs.unshift(`录音 #${recording.recording_id} 本地转写 ${local.latency_ms.toFixed(0)}ms · RTF ${local.realtime_factor.toFixed(2)} · 加载 ${local.model_load_ms}ms`);await invoke("mark_recording_processed",{recordingId:recording.recording_id,status:"linking memory"});const context={tasks:quests.map(value=>({id:value.id,title:value.title,body:value.body,personId:value.personId??null})),people:people.map(value=>({id:value.id,name:value.name}))},result=await analyzeConversation(transcript.text,context),insight=result.insight;let taskIds=[...insight.taskIds];if(insight.followUps.length){const linked=quests.find(value=>value.id===taskIds[0]);if(linked){for(const step of insight.followUps.map(safe))if(step&&!linked.steps.includes(step))linked.steps.push(step)}else{const generated:Quest={id:`conversation-${recording.recording_id}`,group:"突发任务",title:safe(insight.followUps[0]).slice(0,28),meta:"对话提取 · 待安排",body:safe(insight.summary),priority:"普通",progress:0,steps:insight.followUps.map(safe),personId:insight.personIds[0],person:people.find(value=>value.id===insight.personIds[0])?.name,reward:"记忆经验 +5"};quests.unshift(generated);taskIds=[generated.id]}}
  const linkedTitles=taskIds.map(id=>quests.find(value=>value.id===id)?.title).filter((value):value is string=>Boolean(value));for(const personId of insight.personIds){const target=people.find(value=>value.id===personId);if(!target)continue;target.affinity=Math.max(0,Math.min(100,target.affinity+insight.affinityDelta));target.seen="刚刚 · 对话记录";if(insight.story&&!target.story.includes(insight.story))target.story=`${target.story}\n\n新故事 · ${insight.story}`;for(const title of linkedTitles)if(!target.quests.includes(title))target.quests.unshift(title)}const item=memories.find(value=>value.id===`recording-${recording.recording_id}`);if(item){item.title=safe(insight.summary).slice(0,48);item.summary=safe(insight.summary);item.transcript=safe(transcript.text).slice(0,1200);item.personIds=insight.personIds;item.taskIds=taskIds;item.meta=`${insight.personIds.map(id=>people.find(value=>value.id===id)?.name).filter(Boolean).join("、")||"未关联人物"} · ${linkedTitles.join("、")||"未关联既有任务"} · ${transcript.model}`}saveQuests();savePeople();saveMemories();logs.unshift(`录音 #${recording.recording_id} 已总结 · 人物 ${insight.personIds.length} / 任务 ${taskIds.length}`);await invoke("mark_recording_processed",{recordingId:recording.recording_id,status:"summarized and linked"});if(tab==="settings"||tab==="topia"||tab==="people")render()}
 catch(error){const message=error instanceof Error?error.message:"录音处理失败";logs.unshift(`录音 #${recording.recording_id} · ${message}`);await invoke("mark_recording_processed",{recordingId:recording.recording_id,status:`error: ${message.slice(0,90)}`}).catch(()=>undefined);if(!asrDownload?.ready){processingRecordings.delete(recording.recording_id);recordingRetryAfter.set(recording.recording_id,Date.now()+15000);void refreshModelDownload(true)}}
}
async function syncGlassSettings(){if(state.phase!=="ready"||!state.session_id||syncedSessionId===state.session_id)return;syncedSessionId=state.session_id;try{await invoke("set_person_alert",{enabled:glassSettings.personAlert==="poster"});await invoke("set_perception",{enabled:perception,intervalSeconds:glassSettings.intervalSeconds,width:glassSettings.width,quality:glassSettings.quality});logs.unshift(`眼镜参数已同步 · ${glassSettings.intervalSeconds}s / ${glassSettings.width}px / Q${glassSettings.quality}`)}catch{syncedSessionId=null}}
async function refreshModelDownload(force=false){const now=Date.now();if(!force&&(tab!=="settings"||setting!=="intelligence")&&!state.last_recording)return;if(!force&&now-lastModelStatusFetch<1500)return;lastModelStatusFetch=now;try{const next=await invoke<ModelDownloadStatus>("model_download_status"),changed=JSON.stringify(next)!==JSON.stringify(asrDownload);asrDownload=next;if(changed&&tab==="settings"&&setting==="intelligence")render()}catch{/* browser preview or Android plugin not available */}}
async function refresh(){try{state=await invoke<State>("session_state");void syncGlassSettings();const changed=ingestState();if(state.last_recording)void processRecording(state.last_recording);if(tab==="settings"&&setting==="testing"||changed&&(tab==="topia"||tab==="people"||tab==="settings"&&setting==="memory"))render()}catch{/* web preview */}}
async function connectGlasses(silent=false){
 if(connecting)return;connecting=true;
 try{const devices=await invoke<{name:string;address:string}[]>("paired_glasses");const d=devices.find(x=>/rokid|glass/i.test(x.name))??devices[0];if(!d)throw 0;syncedSessionId=null;state=await invoke<State>("begin_session",{glassAddress:d.address});localStorage.setItem("realtopia.glassName",d.name);logs.unshift(`已选择 ${d.name}，正在建立 CXR 会话`);if(!silent)toast(`正在连接 ${d.name}`);render()}
 catch{if(!silent)toast("未找到已配对眼镜，请打开蓝牙设置")}
 finally{connecting=false}
}
async function capture(mode:"cold"|"hot"){try{const r=await invoke<{request_id:number}>("request_capture",{mode,width:glassSettings.width,quality:glassSettings.quality});logs.unshift(`#${r.request_id} ${mode} · ${glassSettings.width}px / Q${glassSettings.quality}`);toast(`拍摄 #${r.request_id} 已发送`);setTimeout(refresh,900)}catch{toast("眼镜尚未连接")}}
const safe=(value:string)=>value.replace(/[<>&"']/g," ").replace(/\s+/g," ").trim();
async function startMoodCheckIn(){
 moodError="";moodTranscript="";moodPhase="listening";render();
 try{
  await new Promise(resolve=>setTimeout(resolve,250));
  const speech=await invoke<MoodSpeechResult>("listen_mood");moodTranscript=safe(speech.transcript).slice(0,4000);if(!moodTranscript)throw new Error("没有听清，请再说一次");moodPhase="analyzing";render();
  const {analysis,model}=await analyzeMood(moodTranscript);currentMood={...analysis,transcript:moodTranscript,model:model.model,analyzedAt:new Date().toISOString()};saveMood();
  const profile=moodProfiles[analysis.mood],time=new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});memories.unshift({id:`mood-${Date.now()}`,time,title:`心情 · ${profile.label}`,meta:`强度 ${analysis.intensity} · ${model.model}`,kind:"mood",summary:analysis.summary,transcript:moodTranscript,mood:analysis.mood,intensity:analysis.intensity});saveMemories();logs.unshift(`心情分析完成 · ${profile.label} ${analysis.intensity} · ${model.latencyMs}ms`);moodPhase="result";render();
 }catch(error){const message=error instanceof Error?error.message:String(error);if(message.includes("心情语音已取消")){moodPhase="idle";render();return}moodError=message||"心情分析失败";moodPhase="error";render()}
}
async function cancelMoodCheckIn(){moodPhase="idle";moodTranscript="";render();try{await invoke("cancel_mood_listen")}catch{/* browser preview or listener already ended */}}
function bind(){
 document.querySelectorAll<HTMLElement>("[data-tab]").forEach(x=>x.onclick=()=>{tab=x.dataset.tab as Tab;render()});
 document.querySelectorAll<HTMLElement>("[data-setting]").forEach(x=>x.onclick=()=>{setting=x.dataset.setting as Setting;memoryDrawerOpen=false;render()});
 document.querySelectorAll<HTMLElement>("[data-quest]").forEach(x=>x.onclick=()=>{quest=quests.find(q=>q.id===x.dataset.quest)!;if(x.dataset.openQuest)tab="quests";render()});
 document.querySelectorAll<HTMLElement>("[data-quest-filter]").forEach(x=>x.onclick=()=>{questFilter=x.dataset.questFilter as QuestFilter;const visible=quests.filter(item=>questFilter==="all"||(questFilter==="done"?item.progress===100:item.progress<100));if(!visible.includes(quest)&&visible[0])quest=visible[0];render()});
 document.querySelectorAll<HTMLElement>("[data-person]").forEach(x=>x.onclick=()=>{person=people.find(p=>p.id===x.dataset.person)!;peoplePanel="quests";render()});
 document.querySelectorAll<HTMLElement>("[data-person-panel]").forEach(x=>x.onclick=()=>{peoplePanel=x.dataset.personPanel as PersonPanel;render()});
 document.querySelectorAll<HTMLElement>("[data-memory]").forEach(x=>x.onclick=()=>{selectedMemoryId=x.dataset.memory!;if(tab==="people"){tab="settings";setting="memory"}memoryDrawerOpen=true;render()});
 document.querySelectorAll<HTMLElement>("[data-close-memory]").forEach(x=>x.onclick=()=>{memoryDrawerOpen=false;render()});
 document.querySelectorAll<HTMLElement>("[data-group]").forEach(x=>x.onclick=()=>{const g=x.dataset.group!;collapsed.has(g)?collapsed.delete(g):collapsed.add(g);render()});
 document.querySelectorAll<HTMLElement>("[data-step]").forEach(x=>x.onclick=()=>{const index=Number(x.dataset.step),completed=Math.round(quest.progress*quest.steps.length/100);quest.progress=Math.round(100*(index<completed?index:index+1)/quest.steps.length);saveQuests();if(quest.progress===100&&!memories.some(item=>item.id===`complete-${quest.id}`)){memories.unshift({id:`complete-${quest.id}`,time:new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"}),title:`任务完成 · ${quest.title}`,meta:`世界变化已保存 · ${quest.reward}`,kind:"task"});saveMemories()}render()});
 document.querySelector("#record-task")?.addEventListener("click",()=>toast("任务会从眼镜对话中自动提炼"));
 const openMood=()=>{moodDialogOpen=true;moodPhase="idle";moodError="";render()};document.querySelector("#record-mood")?.addEventListener("click",openMood);document.querySelector("#today-mood")?.addEventListener("click",openMood);document.querySelector("#world-mood")?.addEventListener("click",openMood);
 document.querySelector("#start-mood-listen")?.addEventListener("click",()=>void startMoodCheckIn());document.querySelector("#cancel-mood-listen")?.addEventListener("click",()=>void cancelMoodCheckIn());
 document.querySelector("#finish-mood-listen")?.addEventListener("click",()=>{const button=document.querySelector<HTMLButtonElement>("#finish-mood-listen");if(button){button.disabled=true;button.textContent="正在识别…"}void invoke("finish_mood_listen").catch(error=>{moodError=error instanceof Error?error.message:String(error);moodPhase="error";render()})});
 document.querySelector("#close-mood")?.addEventListener("click",()=>{const wasListening=moodPhase==="listening";moodDialogOpen=false;moodPhase="idle";render();if(wasListening)void invoke("cancel_mood_listen").catch(()=>undefined)});document.querySelector("#finish-mood")?.addEventListener("click",()=>{moodDialogOpen=false;moodPhase="idle";render()});
 document.querySelector("#open-cloud-settings")?.addEventListener("click",()=>{moodDialogOpen=false;moodPhase="idle";tab="settings";setting="intelligence";render()});
 document.querySelector("#choose")?.addEventListener("click",()=>connectGlasses());
 document.querySelector("#bt")?.addEventListener("click",()=>invoke("open_bluetooth_settings").catch(()=>toast("请打开系统蓝牙设置")));
 document.querySelector<HTMLInputElement>("#perception")?.addEventListener("change",async e=>{const old=perception;perception=(e.target as HTMLInputElement).checked;try{await invoke("set_perception",{enabled:perception,intervalSeconds:glassSettings.intervalSeconds,width:glassSettings.width,quality:glassSettings.quality});localStorage.setItem("realtopia.perception",perception?"on":"off");toast(`持续感知已${perception?"开启":"关闭"}`)}catch{perception=old;(e.target as HTMLInputElement).checked=old;toast("眼镜尚未连接，设置未更改")}});
 const interval=document.querySelector<HTMLInputElement>("#capture-interval");interval?.addEventListener("input",()=>{glassSettings.intervalSeconds=Number(interval.value);const label=document.querySelector("#capture-interval-label");if(label)label.textContent=`${glassSettings.intervalSeconds} 秒`;saveGlassSettings()});interval?.addEventListener("change",()=>{if(perception)invoke("set_perception",{enabled:true,intervalSeconds:glassSettings.intervalSeconds,width:glassSettings.width,quality:glassSettings.quality}).then(()=>toast("自动拍摄参数已同步到眼镜")).catch(()=>toast("参数已保存，将在下次连接时同步"))});
 const syncCaptureParameters=()=>{saveGlassSettings();if(perception)invoke("set_perception",{enabled:true,intervalSeconds:glassSettings.intervalSeconds,width:glassSettings.width,quality:glassSettings.quality}).then(()=>toast("拍摄参数已同步到眼镜")).catch(()=>toast("参数已保存，将在下次连接时同步"))};
 const quality=document.querySelector<HTMLInputElement>("#capture-quality");quality?.addEventListener("input",()=>{glassSettings.quality=Number(quality.value);const label=document.querySelector("#capture-quality-label");if(label)label.textContent=quality.value;saveGlassSettings()});quality?.addEventListener("change",syncCaptureParameters);
 document.querySelector<HTMLSelectElement>("#capture-width")?.addEventListener("change",event=>{glassSettings.width=Number((event.target as HTMLSelectElement).value);syncCaptureParameters()});
 document.querySelector<HTMLSelectElement>("#person-alert")?.addEventListener("change",event=>{glassSettings.personAlert=(event.target as HTMLSelectElement).value as GlassSettings["personAlert"];saveGlassSettings();invoke("set_person_alert",{enabled:glassSettings.personAlert==="poster"}).then(()=>toast("人物提醒方式已同步")).catch(()=>toast("提醒方式已保存，将在下次连接时同步"))});
 document.querySelectorAll<HTMLElement>("[data-test]").forEach(x=>x.onclick=()=>{const t=x.dataset.test;if(t==="cold"||t==="hot")capture(t);else if(t==="bench")["cold","hot","hot","hot","hot","hot"].forEach((m,i)=>setTimeout(()=>capture(m as "cold"|"hot"),i*1000));else toast("请长按眼镜物理按钮开始录音")});
 const modelSettings=modelHub.load(),modelKey=document.querySelector<HTMLInputElement>("#model-key"),modelProvider=document.querySelector<HTMLInputElement>("#model-provider"),modelBaseUrl=document.querySelector<HTMLInputElement>("#model-base-url"),modelName=document.querySelector<HTMLInputElement>("#model-name"),modelStt=document.querySelector<HTMLInputElement>("#model-stt");if(modelProvider)modelProvider.value=modelSettings.cloud.provider;if(modelBaseUrl)modelBaseUrl.value=modelSettings.cloud.baseUrl;if(modelName)modelName.value=modelSettings.cloud.model;if(modelStt)modelStt.value=modelSettings.cloud.sttModel;
 document.querySelector("#show-key")?.addEventListener("click",()=>{if(modelKey)modelKey.type=modelKey.type==="password"?"text":"password"});
 const readModelForm=()=>{const settings=modelHub.load(),baseUrl=modelBaseUrl?.value.trim()??settings.cloud.baseUrl;if(!/^https:\/\//.test(baseUrl))throw new Error("Base URL 必须使用 HTTPS");settings.cloud={provider:modelProvider?.value.trim()||"阿里云百炼 · OpenAI Compatible",baseUrl,model:modelName?.value.trim()||settings.cloud.model,sttModel:modelStt?.value.trim()||settings.cloud.sttModel,hasApiKey:settings.cloud.hasApiKey};settings.routing.privateOnEdge=document.querySelector<HTMLInputElement>("#private")?.checked??true;settings.routing.complexOnCloud=document.querySelector<HTMLInputElement>("#cloud")?.checked??true;return settings};
 const saveModelForm=async()=>modelHub.saveSecureConfig(readModelForm(),modelKey?.value);
 document.querySelector("#test-model")?.addEventListener("click",async()=>{try{await saveModelForm();const result=await modelHub.testCloud();toast(`连接成功 · ${result.model} · ${result.latencyMs} ms`)}catch(error){toast(error instanceof Error?error.message:"云端连接失败")}});
 document.querySelector("#save-model")?.addEventListener("click",async()=>{try{await saveModelForm();if(state.last_recording){processingRecordings.delete(state.last_recording.recording_id);void processRecording(state.last_recording)}toast("配置与密钥已安全保存");render()}catch(error){toast(error instanceof Error?error.message:"模型配置无效")}});document.querySelector("#clear-model-key")?.addEventListener("click",async()=>{if(!confirm("清除本机安全存储中的云端 API Key？"))return;try{await modelHub.clearSecureApiKey();toast("API Key 已清除");render()}catch{toast("API Key 清除失败")}});document.querySelector("#refresh")?.addEventListener("click",refresh);document.querySelector("#clear")?.addEventListener("click",()=>{logs=[];render()});
 document.querySelector("#start-asr-download")?.addEventListener("click",async()=>{try{await invoke("start_asr_download");toast("ASR 模型已加入系统下载队列");setTimeout(()=>void refreshModelDownload(true),500)}catch(error){toast(error instanceof Error?error.message:"ASR 下载启动失败")}});
 document.querySelectorAll<HTMLElement>("[data-model-repo]").forEach(button=>button.onclick=()=>invoke("open_model_repository",{modelId:button.dataset.modelRepo}).catch(()=>toast("无法打开 ModelScope 页面")));
 document.querySelector<HTMLInputElement>("#memory-search")?.addEventListener("input",event=>{memoryQuery=(event.target as HTMLInputElement).value;render();const next=document.querySelector<HTMLInputElement>("#memory-search");next?.focus();next?.setSelectionRange(next.value.length,next.value.length)});
 document.querySelector("#delete-memory")?.addEventListener("click",()=>{const target=memories.find(item=>item.id===selectedMemoryId);if(target&&confirm(`删除记忆“${target.title}”？此操作无法撤销。`)){memories=memories.filter(item=>item.id!==target.id);selectedMemoryId=memories[0]?.id??"";memoryDrawerOpen=false;saveMemories();toast("记忆已删除");render()}});
 document.querySelector("#clear-memory")?.addEventListener("click",()=>{if(memories.length&&confirm(`清除本机全部 ${memories.length} 条记忆？此操作无法撤销。`)){memories=[];selectedMemoryId="";saveMemories();toast("全部记忆已清除");render()}});
 document.querySelector("#export-memory")?.addEventListener("click",()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),memories},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`realtopia-memory-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("记忆档案已导出")});
 document.querySelector("#enroll-person")?.addEventListener("click",async()=>{try{await invoke("enroll_last_face",{personId:person.id});toast(`已将最近人脸录入 ${person.name}`)}catch{toast("没有可录入的人脸，请先拍摄清晰正脸")}})
}
async function bootstrap(){await modelHub.refreshSecureConfig().catch(()=>undefined);render();await refresh();void refreshModelDownload(true);if(!state.session_id)await connectGlasses(true)}
void bootstrap();setInterval(()=>{void refresh();void refreshModelDownload()},1000);
